### ISSUE TITLE
Environment variable `SHELL` set to `pw->pw_dir`.

### ISSUE THREAD

**Issue by jfrech** [maandree/asroot#1]
In lines `164` and `169` of file `asroot.c`, `pw_dir` should probably be changed to `pw_shell`.
https://github.com/maandree/asroot/blob/e3784823610347e5908e119189c9a51e22c609b2/asroot.c#L164
https://github.com/maandree/asroot/blob/e3784823610347e5908e119189c9a51e22c609b2/asroot.c#L169

**Comment by maandree** [comment]
Thank you, this has been is correct now.
